<?php

namespace AppBundle\Repository;

/**
 * CategorieDeServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieDeServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
