<?php

namespace AppBundle\Repository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository
{

    public function search($a){
        $qb = $this->createQueryBuilder('user');
        $q = $qb->addSelect('user')
            ->where('user.type = :t');
        $q->setParameter('t',$a);
        $q = $q->getQuery();
        $q->getResult();
    }
}
