# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    app.functions.annuaire.user: user_courant
#    parameter_name: value

services:
    app.form.profile:
        class: AppBundle\Form\ProfileType
        tags:
            - {name: form.type, alias: app_user_profile}

    app.functions.annuaire:
        class: AppBundle\Functions\Annuaire
        arguments: ['@security.token_storage']


#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

